version: '3.2'
services:
  database:
    environment:
      - POSTGRES_DB=books_test
    image: postgres

  console:
    depends_on:
      - migrated_database
    build: ./backend
    environment:
      - HANAMI_ENV=test
      - DATABASE_URL=postgres://postgres@twist_database_1/books_test
    command: bash -c "sleep 5 && bundle exec hanami console"

  migrated_database:
    depends_on:
      - database
    build: ./backend
    command: bash -c "sleep 5 && bundle exec hanami db migrate"
    environment:
      - HANAMI_ENV=test

  backend:
    build: ./backend
    hostname: backend
    environment:
      - HANAMI_ENV=test
      - DATABASE_URL=postgres://postgres@twist_database_1/books_test
      - PORT=80
    command: scripts/server

    depends_on:
      - database

  frontend:
    build: ./frontend
    environment:
      - API_HOST=http://backend:2300
    ports:
      - 80
    depends_on:
      - backend

  tests:
    depends_on:
      - migrated_database
      - frontend
    build: ./backend
    command: bash -c "sleep 5 && bundle exec rspec spec/features"
    environment:
      - DATABASE_URL=postgres://postgres@twist_database_1/books_test
      - HEADLESS=1
      - FRONTEND_APP_URL=http://frontend
      - HANAMI_ENV=test

  screenshots:
    depends_on:
      - migrated_database
      - frontend
    build: ./screenshots
    command: google-chrome --headless --no-sandbox --disable-gpu --screenshot=/opt/app/static/screenshot.png --window-size=1280,1696 http://frontend
    volumes:
      - type: bind
        source: ./static
        target: /opt/app/static

