AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "Capfile"
    - "config/deploy/**/*"
    - "lib/tasks/**"
    - "repos/**/*"
    - "sbin/*"

Rails:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceAroundOperators:
  Exclude:
    - Rakefile

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/PercentLiteralDelimiters:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Exclude:
    - "apps/web/controllers/**/*"

Metrics/BlockLength:
  Exclude:
    - "apps/web/application.rb"
    - "spec/**/*"

Naming/VariableNumber:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
